/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JToggleButton;

/**
 *
 * @author Paulina
 */
public class VistaMenuPrincipalBiblioteca extends javax.swing.JFrame {

    /**
     * Creates new form VistaMenuPrincipal
     */
    public VistaMenuPrincipalBiblioteca() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btncatalogo = new javax.swing.JToggleButton();
        btnprestamos = new javax.swing.JToggleButton();
        btnreportes = new javax.swing.JToggleButton();
        btnsalir = new javax.swing.JToggleButton();
        Desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuCrudpersonas = new javax.swing.JMenu();
        MitenCrudPersonas = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jToolBar1.setRollover(true);

        btncatalogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/imagenes/How-to.png"))); // NOI18N
        btncatalogo.setText("Catalogo");
        btncatalogo.setToolTipText("Mantenimiento de Clientes");
        btncatalogo.setFocusable(false);
        btncatalogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btncatalogo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btncatalogo);

        btnprestamos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/imagenes/Shopping cart.png"))); // NOI18N
        btnprestamos.setText("Prestamos");
        btnprestamos.setFocusable(false);
        btnprestamos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnprestamos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnprestamos);

        btnreportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/imagenes/Report.png"))); // NOI18N
        btnreportes.setText("Reportes");
        btnreportes.setFocusable(false);
        btnreportes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnreportes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnreportes);

        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/imagenes/Exit.png"))); // NOI18N
        btnsalir.setText("Salir");
        btnsalir.setFocusable(false);
        btnsalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnsalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnsalir);

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 501, Short.MAX_VALUE)
        );

        mnuCrudpersonas.setText("Menu");

        MitenCrudPersonas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/imagenes/Boss.png"))); // NOI18N
        MitenCrudPersonas.setText("Añadir Libros");
        mnuCrudpersonas.add(MitenCrudPersonas);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/imagenes/Report.png"))); // NOI18N
        jMenuItem2.setText("Reportes");
        mnuCrudpersonas.add(jMenuItem2);

        jMenuBar1.add(mnuCrudpersonas);

        jMenu1.setText("Institucion Educativa");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/imagenes/About.png"))); // NOI18N
        jMenuItem1.setText("Mision");
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Vision");
        jMenu1.add(jMenuItem3);

        jMenuItem6.setText("Ubicacion");
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Contactos");

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/imagenes/Dial.png"))); // NOI18N
        jMenuItem4.setText("Telefono");
        jMenu2.add(jMenuItem4);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/imagenes/User group.png"))); // NOI18N
        jMenuItem5.setText("Redes Sociales");
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Ayuda");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE))
            .addComponent(Desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Desktop))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JDesktopPane getDesktop() {
        return Desktop;
    }

    public void setDesktop(JDesktopPane Desktop) {
        this.Desktop = Desktop;
    }

    public JMenuItem getMitenCrudPersonas() {
        return MitenCrudPersonas;
    }

    public void setMitenCrudPersonas(JMenuItem MitenCrudPersonas) {
        this.MitenCrudPersonas = MitenCrudPersonas;
    }

    public JMenu getMnuCrudpersonas() {
        return mnuCrudpersonas;
    }

    public void setMnuCrudpersonas(JMenu mnuCrudpersonas) {
        this.mnuCrudpersonas = mnuCrudpersonas;
    }

    public JToggleButton getBtncatalogo() {
        return btncatalogo;
    }

    public void setBtncatalogo(JToggleButton btncatalogo) {
        this.btncatalogo = btncatalogo;
    }

    public JToggleButton getBtnprestamos() {
        return btnprestamos;
    }

    public void setBtnprestamos(JToggleButton btnprestamos) {
        this.btnprestamos = btnprestamos;
    }

    public JToggleButton getBtnreportes() {
        return btnreportes;
    }

    public void setBtnreportes(JToggleButton btnreportes) {
        this.btnreportes = btnreportes;
    }

    public JToggleButton getBtnsalir() {
        return btnsalir;
    }

    public void setBtnsalir(JToggleButton btnsalir) {
        this.btnsalir = btnsalir;
    }

    


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenuItem MitenCrudPersonas;
    private javax.swing.JToggleButton btncatalogo;
    private javax.swing.JToggleButton btnprestamos;
    private javax.swing.JToggleButton btnreportes;
    private javax.swing.JToggleButton btnsalir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu mnuCrudpersonas;
    // End of variables declaration//GEN-END:variables
}
