/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JToggleButton;

/**
 *
 * @author Paulina
 */
public class VistaMenuPrincipalBiblioteca extends javax.swing.JFrame {

    /**
     * Creates new form VistaMenuPrincipal
     */
    public VistaMenuPrincipalBiblioteca() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btncatalogo = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        Desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuCrudpersonas = new javax.swing.JMenu();
        MitenCrudPersonas = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jToolBar1.setRollover(true);

        btncatalogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/imagenes/How-to.png"))); // NOI18N
        btncatalogo.setText("Catalogo");
        btncatalogo.setToolTipText("Mantenimiento de Clientes");
        btncatalogo.setFocusable(false);
        btncatalogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btncatalogo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btncatalogo);

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/imagenes/Shopping cart.png"))); // NOI18N
        jToggleButton1.setText("Prestamos");
        jToggleButton1.setFocusable(false);
        jToggleButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jToggleButton1);

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 501, Short.MAX_VALUE)
        );

        mnuCrudpersonas.setText("Opciones");

        MitenCrudPersonas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/imagenes/Boss.png"))); // NOI18N
        MitenCrudPersonas.setText("Añadir Libros");
        mnuCrudpersonas.add(MitenCrudPersonas);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/imagenes/Report.png"))); // NOI18N
        jMenuItem2.setText("Reportes");
        mnuCrudpersonas.add(jMenuItem2);

        jMenuBar1.add(mnuCrudpersonas);

        jMenu4.setText("Ayuda");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE))
            .addComponent(Desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Desktop))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JDesktopPane getDesktop() {
        return Desktop;
    }

    public void setDesktop(JDesktopPane Desktop) {
        this.Desktop = Desktop;
    }

    public JMenuItem getMitenCrudPersonas() {
        return MitenCrudPersonas;
    }

    public void setMitenCrudPersonas(JMenuItem MitenCrudPersonas) {
        this.MitenCrudPersonas = MitenCrudPersonas;
    }

    public JMenu getMnuCrudpersonas() {
        return mnuCrudpersonas;
    }

    public void setMnuCrudpersonas(JMenu mnuCrudpersonas) {
        this.mnuCrudpersonas = mnuCrudpersonas;
    }

    public JToggleButton getBtncatalogo() {
        return btncatalogo;
    }

    public void setBtncatalogo(JToggleButton btncatalogo) {
        this.btncatalogo = btncatalogo;
    }



    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenuItem MitenCrudPersonas;
    private javax.swing.JToggleButton btncatalogo;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu mnuCrudpersonas;
    // End of variables declaration//GEN-END:variables
}
